// Get all milestone
export const GET_MILESTONE_FIND_REQUEST = "GET_MILESTONE_FIND_REQUEST";
export const GET_MILESTONE_FIND_SUCCESS = "GET_MILESTONE_FIND_SUCCESS";
export const GET_MILESTONE_FIND_ERR = "GET_MILESTONE_FIND_ERR";

// find all templates
export const TEMPLATE_LIST_FIND_REQUEST = "TEMPLATE_LIST_FIND_REQUEST";
export const TEMPLATE_LIST_FIND_SUCCESS = "TEMPLATE_LIST_FIND_SUCCESS";
export const TEMPLATE_LIST_FIND_ERR = "TEMPLATE_LIST_FIND_ERR";

// find template by id
export const TEMPLATE_LIST_FIND_BY_ID_REQUEST = "TEMPLATE_LIST_FIND_BY_ID_REQUEST";
export const TEMPLATE_LIST_FIND_BY_ID_SUCCESS = "TEMPLATE_LIST_FIND_BY_ID_SUCCESS";
export const TEMPLATE_LIST_FIND_BY_ID_ERR = "TEMPLATE_LIST_FIND_BY_ID_ERR";

// get template type
export const GET_TEMPLATE_TYPE_REQUEST = "GET_TEMPLATE_TYPE_REQUEST";
export const GET_TEMPLATE_TYPE_SUCCESS = "GET_TEMPLATE_TYPE_SUCCESS";
export const GET_TEMPLATE_TYPE_ERR = "GET_TEMPLATE_TYPE_ERR";

// get color 
export const GET_COLOR_REQUEST = "GET_COLOR_REQUEST";
export const GET_COLOR_SUCCESS = "GET_COLOR_SUCCESS";
export const GET_COLOR_ERR = "GET_COLOR_ERR";
