// find all templates
export const TEMPLATE_LIST_FIND_REQUEST = "TEMPLATE_LIST_FIND_REQUEST";
export const TEMPLATE_LIST_FIND_SUCCESS = "TEMPLATE_LIST_FIND_SUCCESS";
export const TEMPLATE_LIST_FIND_ERR = "TEMPLATE_LIST_FIND_ERR";

// find template by id
export const TEMPLATE_LIST_FIND_BY_ID_REQUEST = "TEMPLATE_LIST_FIND_BY_ID_REQUEST";
export const TEMPLATE_LIST_FIND_BY_ID_SUCCESS = "TEMPLATE_LIST_FIND_BY_ID_SUCCESS";
export const TEMPLATE_LIST_FIND_BY_ID_ERR = "TEMPLATE_LIST_FIND_BY_ID_ERR";

// find template by id
export const LIST_ALL_MILESTONE_REQUEST = "LIST_ALL_MILESTONE_REQUEST";
export const LIST_ALL_MILESTONE_SUCCESS = "LIST_ALL_MILESTONE_SUCCESS";
export const LIST_ALL_MILESTONE_ERR = "LIST_ALL_MILESTONE_ERR";

// find template by id
export const GET_TEMPLATE_TYPE_REQUEST = "GET_TEMPLATE_TYPE_REQUEST";
export const GET_TEMPLATE_TYPE_SUCCESS = "GET_TEMPLATE_TYPE_SUCCESS";
export const GET_TEMPLATE_TYPE_ERR = "GET_TEMPLATE_TYPE_ERR";
